services:
  restaurant_service:
    build:
      context: ../../
      dockerfile: services/restaurant/Dockerfile
    container_name: restaurant_service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ../../shared:/opt/shared
    ports:
      - "8003:8000"
    env_file:
      - ../../.env
    environment:
      - PYTHONPATH=/app:/opt
      - DATABASE_URL=postgres://${RESTAURANT_DB_USER}:${RESTAURANT_DB_PASSWORD}@postgres_restaurant:5432/${RESTAURANT_DB_NAME}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/2
    depends_on:
      postgres_restaurant:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - tastify_network