# Generated by Django 5.1.4 on 2026-07-11 13:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'db_table': 'menu_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('prep_time_minutes', models.SmallIntegerField(default=15, verbose_name='Preparation time (minutes)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menucategory', verbose_name='Menu Category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('is_required', models.BooleanField(default=False, help_text='Must the user select an option from this group? (e.g., Size is required)', verbose_name='Is Required')),
                ('min_selections', models.SmallIntegerField(default=0, verbose_name='Minimum Selections')),
                ('max_selections', models.SmallIntegerField(default=1, verbose_name='Maximum Selections')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Display Order')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='menus.menuitem', verbose_name='Menu Item')),
            ],
            options={
                'verbose_name': 'Modifier Group',
                'verbose_name_plural': 'Modifier Groups',
                'db_table': 'modifier_groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('weight_grams', models.SmallIntegerField(blank=True, null=True, verbose_name='Weight in grams')),
                ('calories', models.SmallIntegerField(blank=True, null=True, verbose_name='Calories')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='Allergens')),
                ('ingredients', models.JSONField(blank=True, default=list, verbose_name='Ingredients')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Is Spicy')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Is Vegetarian')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Is Vegan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Product (Base Dish)',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Option Name')),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Extra Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Display Order')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menus.modifiergroup', verbose_name='Modifier Group')),
                ('linked_product', models.ForeignKey(blank=True, help_text='If this option is a specific dish, link it here to pull ingredients/allergens.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_options', to='menus.product', verbose_name='Linked Product')),
            ],
            options={
                'verbose_name': 'Modifier Option',
                'verbose_name_plural': 'Modifier Options',
                'db_table': 'modifier_options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a custom Combo/Set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menus.product', verbose_name='Base Product'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'is_active'], name='menu_catego_restaur_5bcf75_idx'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_category_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('min_selections__lte', models.F('max_selections'))), name='check_min_lte_max_selections'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('min_selections__gte', 0)), name='check_min_selections_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_product_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams__gte', 0), ('weight_grams__isnull', True), _connector='OR'), name='check_product_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('calories__gte', 0), ('calories__isnull', True), _connector='OR'), name='check_product_calories_positive'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.CheckConstraint(condition=models.Q(('extra_price__gte', 0)), name='check_extra_price_positive'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_active', 'is_available'], name='menu_items_categor_96acba_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_item_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='check_menu_item_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('prep_time_minutes__gte', 0)), name='check_prep_time_positive'),
        ),
    ]
