# Generated by Django 5.1.4 on 2026-07-17 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_closed', models.BooleanField(default=False, help_text='Check this if the restaurant is completely closed.', verbose_name='Is Closed')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close Time')),
                ('closes_next_day', models.BooleanField(default=False, help_text='Check this if the restaurant closes after midnight.', verbose_name='Closes Next Day')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Break Start')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Break End')),
                ('date', models.DateField(db_index=True, help_text='Specific date for the exception.', verbose_name='Date')),
                ('reason', models.CharField(blank=True, default='', help_text="E.g., New Year's Eve, Renovation, Staff Party.", max_length=150, verbose_name='Reason')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_schedules', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Holiday Schedule',
                'verbose_name_plural': 'Holiday Schedules',
                'db_table': 'holiday_schedules',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'date'), name='unique_holiday_schedule_per_date'), models.CheckConstraint(condition=models.Q(('is_closed', True), ('closes_next_day', True), ('open_time__lt', models.F('close_time')), _connector='OR'), name='hs_valid_working_hours'), models.CheckConstraint(condition=models.Q(models.Q(('break_end__isnull', True), ('break_start__isnull', True)), ('break_start__lt', models.F('break_end')), _connector='OR'), name='hs_valid_break_hours')],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_closed', models.BooleanField(default=False, help_text='Check this if the restaurant is completely closed.', verbose_name='Is Closed')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close Time')),
                ('closes_next_day', models.BooleanField(default=False, help_text='Check this if the restaurant closes after midnight.', verbose_name='Closes Next Day')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Break Start')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Break End')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0 = Monday, 6 = Sunday', verbose_name='Day of Week')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Working Hour',
                'verbose_name_plural': 'Working Hours',
                'db_table': 'working_hours',
                'ordering': ['restaurant', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'day_of_week'), name='unique_working_hours_per_day'), models.CheckConstraint(condition=models.Q(('is_closed', True), ('closes_next_day', True), ('open_time__lt', models.F('close_time')), _connector='OR'), name='wh_valid_working_hours'), models.CheckConstraint(condition=models.Q(models.Q(('break_end__isnull', True), ('break_start__isnull', True)), ('break_start__lt', models.F('break_end')), _connector='OR'), name='wh_valid_break_hours')],
            },
        ),
    ]
