#services:
#  nginx:
#    image: nginx:1.27-alpine
#    container_name: tastify_nginx
#    restart: unless-stopped
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./conf.d:/etc/nginx/conf.d:ro
#      - nginx_logs:/var/log/nginx
##    depends_on:
##      - auth_service
##      - user_service
##      - restaurant_service
##      - order_service
##      - delivery_service
##      - payment_service
##      - notification_service
##      - media_service
##      - review_service
##      - search_service
##      - analytics_service
##      - billing_service
#    healthcheck:
#      test: [ "CMD", "nginx", "-t" ]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#    networks:
#      - tastify_network
#
#volumes:
#  nginx_logs: