# Generated by Django 5.1.4 on 2026-07-09 10:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Restaurant ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo URL')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Cover URL')),
                ('address', models.CharField(max_length=255, verbose_name='Physical Address')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='City')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Contact Phone')),
                ('cuisine_types', models.JSONField(default=list, help_text="List of strings, e.g., ['pizza', 'sushi']", verbose_name='Cuisine Types')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Minimum Order Amount')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Delivery Fee')),
                ('avg_delivery_time', models.SmallIntegerField(default=30, verbose_name='Average Delivery Time (mins)')),
                ('avg_prep_time', models.SmallIntegerField(default=15, help_text='Used for ML ETA prediction', verbose_name='Average Prep Time (mins)')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Rating Count')),
                ('is_active', models.BooleanField(default=False, help_text='Activated by platform admin', verbose_name='Is Active')),
                ('is_open', models.BooleanField(default=False, help_text='Auto-updated based on working hours', verbose_name='Is Open Now')),
                ('is_accepting_orders', models.BooleanField(default=True, help_text='Manual toggle to temporarily stop receiving orders', verbose_name='Accepting Orders')),
                ('legal_name', models.CharField(blank=True, help_text='For billing and payouts', max_length=200, verbose_name='Legal Name')),
                ('tax_id', models.CharField(blank=True, help_text='For official reports', max_length=50, verbose_name='Tax ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Commission Rate (%)')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Is Promoted')),
                ('promotion_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Promotion Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'is_active', 'is_open'], name='restaurants_city_8d1a56_idx'), models.Index(fields=['city', 'name'], name='restaurants_city_2d3ccf_idx'), models.Index(fields=['-rating'], name='restaurants_rating_422bd4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 0.0), ('rating__lte', 5.0)), name='restaurant_rating_range'), models.CheckConstraint(condition=models.Q(('min_order_amount__gte', 0.0)), name='restaurant_min_order_positive'), models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0.0)), name='restaurant_delivery_fee_positive')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='Auth Service User ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('editor', 'Menu Editor')], default='manager', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Employee',
                'verbose_name_plural': 'Restaurant Employees',
                'db_table': 'restaurant_employees',
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'user_id'), name='unique_restaurant_employee'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('restaurant',), name='unique_owner_per_restaurant')],
            },
        ),
    ]
