# Generated by Django 5.1.4 on 2026-05-31 16:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False, help_text='Unique identifier from the Auth Service.', verbose_name='User ID')),
                ('label', models.CharField(blank=True, default='', help_text="For example: 'Home', 'Work', etc.", max_length=50, verbose_name='Label')),
                ('address_line', models.CharField(max_length=255, verbose_name='Address Line')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('apartment', models.CharField(blank=True, default='', max_length=20, verbose_name='Apartment/Unit')),
                ('entrance', models.CharField(blank=True, default='', max_length=10, verbose_name='Entrance')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Floor')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Addresses',
                'db_table': 'delivery_addresses',
                'ordering': ['-is_default', '-created_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['user_id', 'is_default'], name='delivery_ad_user_id_1a121e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user_id',), name='unique_default_address_per_user'), models.UniqueConstraint(condition=models.Q(('label', ''), _negated=True), fields=('user_id', 'label'), name='unique_label_per_user')],
            },
        ),
    ]
