# Generated by Django 5.1.4 on 2026-06-01 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False, verbose_name='User ID')),
                ('restaurant_id', models.UUIDField(db_index=True, verbose_name='Restaurant ID')),
                ('restaurant_snapshot', models.JSONField(default=dict, verbose_name='Restaurant Snapshot')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
            ],
            options={
                'verbose_name': 'Favorite Restaurant',
                'verbose_name_plural': 'Favorite Restaurants',
                'db_table': 'favorite_restaurants',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'restaurant_id'), name='unique_favorite_restaurant_per_user')],
            },
        ),
    ]
