# Generated by Django 5.1.4 on 2026-06-07 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True, unique=True, verbose_name='Original Order ID')),
                ('user_id', models.UUIDField(db_index=True, verbose_name='User ID')),
                ('restaurant_id', models.UUIDField(verbose_name='Restaurant ID')),
                ('restaurant_name', models.CharField(max_length=200, verbose_name='Restaurant Name')),
                ('restaurant_logo', models.URLField(blank=True, null=True, verbose_name='Restaurant Logo URL')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('items_summary', models.JSONField(default=list, verbose_name='Items Summary')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('delivery_address_short', models.CharField(blank=True, default='', help_text="Short address for the list (e.g. '22 Khreshchatyk Street')", max_length=255, verbose_name='Short Delivery Address')),
                ('rating_given', models.SmallIntegerField(blank=True, null=True, verbose_name='Rating Given')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Order History Item',
                'verbose_name_plural': 'Order History Items',
                'db_table': 'order_history_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
