# Generated by Django 5.1.4 on 2026-05-25 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier from the Auth Service.', primary_key=True, serialize=False, verbose_name='User ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for couriers. Must be unique.', max_length=20, null=True, unique=True, verbose_name='Phone Number')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Avatar URL')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='Bonus Points')),
                ('notification_telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'customer_profiles',
                'ordering': ['-created_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['phone'], name='idx_customer_phone'), models.Index(fields=['notification_telegram'], name='idx_customer_telegram'), models.Index(fields=['created_at'], name='idx_customer_created_at')],
            },
        ),
    ]
