# Generated by Django 5.1.4 on 2026-05-16 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenBlacklist',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=36, unique=True, verbose_name='refresh token')),
                ('user_id', models.UUIDField(db_index=True, verbose_name='user id')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='blacklisted at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'blacklisted refresh token',
                'verbose_name_plural': 'blacklisted refresh tokens',
                'db_table': 'blacklisted_refresh_tokens',
                'ordering': ['-blacklisted_at'],
                'get_latest_by': 'blacklisted_at',
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('blacklisted_at'))), name='check_expires_after_blacklisting')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant Owner'), ('courier', 'Courier'), ('admin', 'Admin')], default='customer', max_length=20, verbose_name='role')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'permissions': [('can_suspend_user', 'Can suspend users from the platform')],
                'indexes': [models.Index(fields=['role'], name='role_idx')],
            },
        ),
    ]
