# Generated by Django 5.1.4 on 2026-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_2fa_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian')], default='en-us', max_length=10, verbose_name='language'),
        ),
    ]
